[build]
  command = "mkdir -p netlify/functions && echo 'Build preparation'"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]
